sudo: true
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - language: rust
      rust: 1.29.2
      install:
        - cargo fmt --version || rustup component add rustfmt-preview
        - cargo clippy --version || rustup component add clippy-preview
      script: make ci-rust
    - language: python
      python: 3.7
      install:
        - pip install pipenv
        - pipenv install --dev
      script: make ci-python

before_cache:
- rm -rf $HOME/.cargo/registry
